import React, { useEffect, useState } from 'react';

export default function SupplierDetailPanel({ isOpen, onClose, supplier }) {
  const [isVisible, setIsVisible] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => setIsVisible(true), 50);
    } else {
      setIsVisible(false);
    }
  }, [isOpen]);

  if (!isOpen || !supplier) return null;

  const handleDownloadReport = async () => {
    setIsDownloading(true);
    
    try {
      // Generate PDF content as HTML and convert to downloadable format
      const reportHTML = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>TrustGraph AI - Supplier Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
    .header { text-align: center; border-bottom: 2px solid #3366cc; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { color: #3366cc; margin: 0; }
    .header p { color: #666; margin: 5px 0; }
    .section { margin-bottom: 25px; }
    .section h2 { color: #3366cc; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
    .score { font-size: 48px; font-weight: bold; text-align: center; color: ${supplier.score >= 80 ? '#4ade80' : supplier.score >= 50 ? '#eab308' : '#f87171'}; }
    .score-label { text-align: center; color: #666; margin-bottom: 20px; }
    .metrics { display: flex; justify-content: space-around; margin: 20px 0; }
    .metric { text-align: center; }
    .metric-value { font-size: 24px; font-weight: bold; color: #333; }
    .metric-label { color: #666; font-size: 12px; }
    .insight { background: #f5f5f5; padding: 15px; border-radius: 8px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; text-align: center; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 8px; border-bottom: 1px solid #eee; }
    td:first-child { font-weight: bold; width: 40%; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🏢 TrustGraph AI</h1>
    <p>Supplier Risk Assessment Report</p>
    <p>Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
  </div>
  
  <div class="section">
    <h2>📊 Supplier Information</h2>
    <table>
      <tr><td>Company Name</td><td>${supplier.name}</td></tr>
      <tr><td>Industry</td><td>${supplier.industry}</td></tr>
      <tr><td>Risk Level</td><td>${supplier.risk}</td></tr>
      <tr><td>Report ID</td><td>RPT-${Date.now()}</td></tr>
    </table>
  </div>
  
  <div class="section">
    <h2>🎯 Trust Score</h2>
    <div class="score">${supplier.score}/100</div>
    <p class="score-label">Based on 500+ data points including financial health, operational metrics, and market sentiment.</p>
  </div>
  
  <div class="section">
    <h2>📈 Operational Metrics</h2>
    <div class="metrics">
      <div class="metric">
        <div class="metric-value">${supplier.details?.paymentDelay || 'N/A'}</div>
        <div class="metric-label">Payment Delay</div>
      </div>
      <div class="metric">
        <div class="metric-value">${supplier.details?.deliveryReliability || 'N/A'}</div>
        <div class="metric-label">Reliability</div>
      </div>
      <div class="metric">
        <div class="metric-value">${supplier.details?.qualityRate || 'N/A'}</div>
        <div class="metric-label">Quality Rate</div>
      </div>
      <div class="metric">
        <div class="metric-value">${supplier.details?.complaintCount || 0}</div>
        <div class="metric-label">Complaints (30d)</div>
      </div>
    </div>
  </div>
  
  <div class="section">
    <h2>💡 AI Insight</h2>
    <div class="insight">
      ${supplier.insight || `Based on comprehensive analysis, ${supplier.name} shows ${supplier.score >= 80 ? 'excellent' : supplier.score >= 50 ? 'moderate' : 'concerning'} patterns. Our AI recommends ${supplier.score >= 80 ? 'continued partnership with confidence' : supplier.score >= 50 ? 'close monitoring of key metrics' : 'immediate review of alternative suppliers'}.`}
    </div>
  </div>
  
  <div class="footer">
    <p>© 2026 TrustGraph AI. Empowering Indian MSMEs with Predictive Intelligence.</p>
    <p>This report is generated by AI analysis and should be used as advisory only.</p>
    <p>For queries, contact: support@trustgraph.ai | 1800-123-4567</p>
  </div>
</body>
</html>
      `;

      // Create a blob with the HTML content
      const blob = new Blob([reportHTML], { type: 'application/html' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${supplier.name.replace(/\s+/g, '_')}_TrustReport_${new Date().toISOString().split('T')[0]}.html`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

    } catch (error) {
      console.error('Download error:', error);
      alert('Failed to generate report. Please try again.');
    } finally {
      setTimeout(() => setIsDownloading(false), 500);
    }
  };

  const handleShare = async () => {
    const shareData = {
      title: `TrustGraph AI - ${supplier.name}`,
      text: `Check out ${supplier.name}'s Trust Score: ${supplier.score}/100. ${supplier.risk} - ${supplier.insight || 'AI-powered supplier risk assessment.'}`,
      url: window.location.href
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        if (err.name !== 'AbortError') {
          // Fallback to clipboard
          navigator.clipboard.writeText(`${shareData.text}\n\n${shareData.url}`);
          alert('Report link copied to clipboard!');
        }
      }
    } else {
      // Fallback - copy to clipboard
      navigator.clipboard.writeText(`${shareData.text}\n\n${window.location.href}`);
      alert('Report link copied to clipboard!');
    }
  };

  const riskScoreColor = supplier.score >= 80 ? 'text-green-400' : supplier.score >= 50 ? 'text-yellow-400' : 'text-red-400';
  const riskBadgeColor = supplier.riskColor === 'emerald' ? 'bg-green-500/20 text-green-400 border-green-500/40' 
    : supplier.riskColor === 'yellow' ? 'bg-yellow-500/20 text-yellow-400 border-yellow-500/40'
    : 'bg-red-500/20 text-red-400 border-red-500/40';

  return (
    <>
      {/* Backdrop */}
      <div 
        className={`absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity duration-300 ${isVisible ? 'opacity-100' : 'opacity-0'}`}
        onClick={onClose}
      />
      
      {/* Slide-in Panel */}
      <div 
        className={`relative w-full max-w-md h-full bg-gradient-to-b from-surface-container via-surface to-surface-container shadow-2xl border-l border-white/20 overflow-hidden transition-transform duration-500 ease-out ${isVisible ? 'translate-x-0' : 'translate-x-full'}`}
        style={{
          background: 'linear-gradient(180deg, rgba(31, 32, 33, 0.98) 0%, rgba(18, 19, 20, 0.99) 100%)',
          boxShadow: '-20px 0 60px rgba(0, 0, 0, 0.5), inset 0 0 100px rgba(0, 245, 255, 0.03)'
        }}
      >
        {/* Decorative gradient orb */}
        <div className="absolute -top-20 -right-20 w-60 h-60 bg-primary/10 rounded-full blur-3xl" />
        <div className="absolute -bottom-20 -left-20 w-40 h-40 bg-primary/5 rounded-full blur-3xl" />
        
        {/* Header */}
        <div className="relative p-6 border-b border-white/10 bg-gradient-to-r from-surface-container to-transparent">
          <div className="flex justify-between items-start">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-3">
                <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider border ${riskBadgeColor}`}>
                  {supplier.risk}
                </span>
                <span className={`text-xs ${riskScoreColor}`}>
                  Score: {supplier.score}
                </span>
              </div>
              <h2 className="text-2xl font-headline-md font-bold text-white mb-1">
                {supplier.name}
              </h2>
              <p className="text-white/60 text-sm">{supplier.industry}</p>
            </div>
            <button 
              onClick={onClose}
              className="w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 text-white/70 hover:text-white transition-all flex items-center justify-center backdrop-blur-sm border border-white/10"
            >
              <span className="material-symbols-outlined">close</span>
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6 overflow-y-auto h-[calc(100%-280px)]">
          
          {/* Trust Score Hero */}
          <div className="relative p-6 rounded-2xl bg-gradient-to-br from-surface-container to-surface/50 border border-white/10">
            <div className="flex items-center gap-6">
              <div className="relative w-28 h-28 flex items-center justify-center shrink-0">
                {/* Animated gradient ring */}
                <svg className="absolute inset-0 w-full h-full -rotate-90" viewBox="0 0 100 100">
                  <circle cx="50" cy="50" r="45" className="fill-none stroke-white/10" strokeWidth="6" />
                  <circle 
                    cx="50" cy="50" r="45" 
                    className="fill-none"
                    strokeWidth="6"
                    strokeLinecap="round"
                    style={{ 
                      stroke: supplier.score >= 80 ? '#4ade80' : supplier.score >= 50 ? '#eab308' : '#f87171',
                      strokeDasharray: 283,
                      strokeDashoffset: 283 - (supplier.score / 100) * 283,
                      transition: 'stroke-dashoffset 1.5s ease-out'
                    }}
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="text-center">
                    <div className={`text-4xl font-bold ${riskScoreColor}`}>{supplier.score}</div>
                    <div className="text-xs text-white/50">/ 100</div>
                  </div>
                </div>
              </div>
              <div>
                <h3 className="font-headline-md text-lg text-white mb-2">Trust Score</h3>
                <p className="text-sm text-white/60 leading-relaxed">
                  Based on 500+ data points including financial health, operational metrics, and market sentiment analysis.
                </p>
              </div>
            </div>
          </div>

          {/* Key Metrics */}
          <div className="space-y-4">
            <h3 className="font-headline-md text-lg text-white">Operational Metrics</h3>
            <div className="grid grid-cols-2 gap-3">
              {[
                { label: 'Payment Delay', value: supplier.details?.paymentDelay || 'N/A', trend: 'down', color: 'green' },
                { label: 'Reliability', value: supplier.details?.deliveryReliability || 'N/A', trend: 'up', color: 'blue' },
                { label: 'Quality Rate', value: supplier.details?.qualityRate || 'N/A', trend: 'up', color: 'green' },
                { label: 'Complaints', value: supplier.details?.complaintCount || 0, trend: 'neutral', color: 'yellow' }
              ].map((metric, i) => (
                <div 
                  key={metric.label}
                  className="p-4 rounded-xl bg-white/5 border border-white/10 backdrop-blur-sm hover:bg-white/10 transition-all"
                  style={{ animation: `fadeSlideUp 0.4s ease-out ${i * 0.1}s both` }}
                >
                  <div className="text-xs text-white/50 uppercase tracking-wide mb-1">{metric.label}</div>
                  <div className="text-xl font-bold text-white">{metric.value}</div>
                  <div className={`text-xs mt-1 flex items-center gap-1 ${
                    metric.trend === 'down' ? 'text-green-400' : 
                    metric.trend === 'up' ? 'text-blue-400' : 'text-yellow-400'
                  }`}>
                    <span className="material-symbols-outlined text-sm">
                      {metric.trend === 'down' ? 'trending_down' : metric.trend === 'up' ? 'trending_up' : 'trending_flat'}
                    </span>
                    {metric.trend === 'down' ? 'Improved' : metric.trend === 'up' ? 'Good' : 'Stable'}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* AI Insight */}
          <div className="p-5 rounded-2xl bg-gradient-to-r from-primary/10 to-primary/5 border border-primary/20 backdrop-blur-sm">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-10 h-10 rounded-xl bg-primary/20 flex items-center justify-center">
                <span className="material-symbols-outlined text-primary">psychology</span>
              </div>
              <div>
                <h4 className="font-bold text-white">AI Insight</h4>
                <p className="text-xs text-white/50">TrustGraph Analysis</p>
              </div>
            </div>
            <p className="text-sm text-white/80 leading-relaxed">
              {supplier.insight || `Based on comprehensive analysis, ${supplier.name} shows ${supplier.score >= 80 ? 'excellent' : supplier.score >= 50 ? 'moderate' : 'concerning'} patterns in their operational and financial behavior. Our AI recommends ${supplier.score >= 80 ? 'continued partnership with confidence' : supplier.score >= 50 ? 'close monitoring of key metrics' : 'immediate review of alternative suppliers'}.`}
            </p>
          </div>

          {/* Timeline */}
          <div className="space-y-3">
            <h3 className="font-headline-md text-lg text-white">Recent Activity</h3>
            {[
              { date: '2 days ago', action: 'Payment received', icon: 'payments', color: 'green' },
              { date: '1 week ago', action: 'Delivery completed', icon: 'local_shipping', color: 'blue' },
              { date: '2 weeks ago', action: 'Quality audit passed', icon: 'verified', color: 'green' },
              { date: '1 month ago', action: 'Contract renewed', icon: 'description', color: 'purple' }
            ].map((item, i) => (
              <div 
                key={i}
                className="flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/10"
              >
                <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                  item.color === 'green' ? 'bg-green-500/20 text-green-400' :
                  item.color === 'blue' ? 'bg-blue-500/20 text-blue-400' :
                  item.color === 'purple' ? 'bg-purple-500/20 text-purple-400' : 'bg-white/10 text-white'
                }`}>
                  <span className="material-symbols-outlined text-sm">{item.icon}</span>
                </div>
                <div className="flex-1">
                  <div className="text-sm text-white">{item.action}</div>
                  <div className="text-xs text-white/50">{item.date}</div>
                </div>
              </div>
            ))}
          </div>

        </div>

        {/* Footer Actions */}
        <div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-surface via-surface/95 to-transparent border-t border-white/10">
          <div className="flex gap-3">
            <button 
              onClick={handleShare}
              className="flex-1 px-4 py-3 rounded-xl bg-white/5 hover:bg-white/10 text-white transition-all border border-white/10 flex items-center justify-center gap-2"
            >
              <span className="material-symbols-outlined text-sm">share</span>
              Share
            </button>
            <button 
              onClick={handleDownloadReport}
              disabled={isDownloading}
              className="flex-1 px-4 py-3 rounded-xl bg-primary hover:bg-primary/90 text-white transition-all font-bold flex items-center justify-center gap-2 shadow-lg shadow-primary/30"
            >
              <span className={`material-symbols-outlined text-sm ${isDownloading ? 'animate-spin' : ''}`}>
                {isDownloading ? 'hourglass_empty' : 'download'}
              </span>
              {isDownloading ? 'Generating...' : 'Download Report'}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}